version: 2
jobs:
  build:
    docker:
      - build: debian:stretch
    steps:
      - checkout
      - run:
          name: Dockerfile
          command: docker-compose up
      - run:
          name: Print the Current Time
          command: date
