version: 2
jobs:
  build:
    docker:
      - build: general
      - volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
